name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: --enable all --source-path **/*.sh

  install:
    name: Installation
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      env:
        CODESPACES: true
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install
      run: ./install.sh
    - name: chezmoi data
      run: '"${HOME}/.local/bin/chezmoi" data'
